
/*
3.60 ◆◆
Consider the following assembly code:

loop:
    movl    %esi, %ecx
    movl    $1, %edx
    xorl    %eax, %eax
    jmp .L2
.L3:
    movq    %rdi, %r8
    andq    %rdx, %r8
    orq     %r8, %rax
    salq    %cl, %rdx
.L2:
    testq   %rdx, %rdx
    jne .L3
    ret

The preceding code was generated by compiling C code that had the following
overall form:
*/

#include <stdint.h>

long loop(long x, long n)
{
    long result = 0;
    long mask;
    for (mask = 1; mask != 0; mask = mask << (int8_t)n) {
        result |= (x & mask);
    }

    return result;
}

/*
Your task is to fill in the missing parts of the C code to get a program
equivalent to the generated assembly code.
You will find it helpful to examine the assembly code before,
during, and after the loop to form a consistent mapping between the registers and the program variables.

A. Which registers hold program values x, n, result, and mask?
B. What are the initial values of result and mask?
C. What is the test condition for mask?
D. How does mask get updated?
E. How does result get updated?
F. Fill in all the missing parts of the C code.

Answers:

A.
x = %rdi
n = %rsi
result = %rax
mask = %edx

B. The initial values of result is 0, and for mask is 1
C. The test condition is that mask should be non zero.
D. mask = mask << n
E. result |= (x & mask)
F. Look at the code above.
*/
